modLoader="javafml"
loaderVersion="[35,)"
logoFile="icon.png"
license="MIT License"

[[mods]]
    modId="stupidmod"
    version="${version}"
    displayName="Stupid Mod"
    authors="Elaviers, BABYRITZER, Zyve"
    description="Assorted fecal features"

[[dependencies.stupidmod]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.stupidmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"