modLoader="javafml"
loaderVersion="[32,)"
[[mods]]
    modId="stupidmod"
    version="${version}"
    displayName="Stupid Mod"
    authors="Elaviers, BABYRITZER, Zyve"
    description="Assorted fecal features"

[[dependencies.stupidmod]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.stupidmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"