modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
[[mods]] #mandatory
modId="stupidmod" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Stupid Mod" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="Elaviers" #optional
description='''
Assorted fecal features
'''

[[dependencies.stupidmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[25,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.stupidmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"