modLoader="javafml"
loaderVersion="[31,)"
logoFile="icon.png"

[[mods]]
    modId="stupidmod"
    version="${version}"
    displayName="Stupid Mod"
    authors="Elaviers, BABYRITZER, Zyve"
    description="Assorted fecal features"

[[dependencies.stupidmod]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.stupidmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"