modLoader="javafml"
loaderVersion="[28,)"
[[mods]]
    modId="stupidmod"
    version="${version}"
    displayName="Stupid Mod"
    authors="Elaviers, BABYRITZER, Zyve"
    description="Assorted fecal features"

[[dependencies.stupidmod]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.stupidmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"